version: "3"

services:
  pack:
    image: lambda-pack
    build:
      context: .
      dockerfile: Dockerfile
    command: ["cp", "/project/index.zip", "/out/index.zip"]
    volumes:
    - ./out:/out
