FROM ruby:2.2-jessie

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  zip \
  tk \
  && rm -rf /var/lib/apt/lists/*

RUN gem install rumbda

WORKDIR /project

CMD ["./pack.sh"]
